In [59]:
%matplotlib inline
import numpy
import matplotlib.pyplot as plt
import functools
import math
import neurons
import random

In [60]:
# training_set = [[1, 1, 0, 0, 0, 0, 0, 0],
#                 [0, 0, 0, 0, 1, 1, 0, 0],
#                 [1, 0, 0, 0, 0, 0, 0, 1],
#                 [0, 0, 0, 1, 1, 0, 0, 0]]

# new_pattern = [1, 1, 1, 0, 0, 0, 0, 0]

training_set = [[1, 0, 0, 1],
                [0, 1, 1, 0],
                [1, 0, 1, 0]]

new_pattern = [1, 0, 1, 1]

neuron_count = len(new_pattern);

#create a hopefield network of n neurons with n weights each.
hopefield_network = [neurons.HopefieldActivationNeuron(numpy.zeros((neuron_count)), 1) 
                    for i in range(neuron_count)] 

def get_states():
    return [hopefield_network[i].state
           for i in range(neuron_count)]

def print_weights():
    for i in range(neuron_count):
        print(hopefield_network[i].weights)
    print()
        
def print_states():
    print(get_states())
    print()
        
print_weights()
print_states()

[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]

[0, 0, 0, 0]



In [61]:
def train(patterns):
    '''
    Train the network with a hebbian process
    '''
    for pattern in patterns:
        for i in range(neuron_count):
            for j in range(neuron_count):
                weight = 0 if (i == j) else hopefield_network[i].weights[j] + ((pattern[i] * pattern[j]) / len(patterns))
                hopefield_network[i].weights[j] = weight

def compute(pattern = None):
    '''
    compute the network state for a new pattern
    '''
    for index, neuron in enumerate(hopefield_network):
        state = pattern if index == 0 and pattern != None else get_states()
        neuron.compute(state)

In [62]:
train(training_set)
print_weights()

[ 0.          0.          0.33333333  0.33333333]
[ 0.          0.          0.33333333  0.        ]
[ 0.33333333  0.33333333  0.          0.        ]
[ 0.33333333  0.          0.          0.        ]



In [63]:
compute(new_pattern)
print_states()

[1, 0, 1, 1]

